name: Realease

on:
  push:
    branches:
      -main
jobs:
  release:
      runs-on: ubuntu-latest


      steps:
      -name: Checkout Code
      uses: actions/checkout@v2

      -name: set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

        -name: Bump Version
        run: npm version minor -m "Bump version to %s"

        -name: Generate Release Notes
        run: npm run generate-release-notes

        -name: Commit and push
        run: |
          git push --follow-tags
          git push origin main

          -name: create Github Realease
          id: create_release
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
            env:
            GITHUB_TOKEN: ${{ SECRETS.github_token }}

            -name: Publish Realease notes
            run: |
            echo "Realease Notes" > release_notes.txt
            cat changelog.md >> release_notes.txt
            gh release upload ${{ steps.create_release.output.upload_url }} ./release_notes.txt

            env:
            GH_CLI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
